### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by tts-sdrissen** [Eun/http-server-action#21]
On every run of the latest http-server-action there is this warning.
I am not sure , because "state" has zero results in the code:

Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Do you experience this error with other projects too?

**Comment by Eun** [comment]
I saw it, the suggestion is to upgrade the `@actions/core` package to `v1.10.0` or greater, what we already have: https://github.com/Eun/http-server-action/blob/master/package-lock.json#L8

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

**Comment by Eun** [comment]
Should be fixed here https://github.com/Eun/http-server-action/pull/22

**Comment by tts-sdrissen** [comment]
*Handkuss*
