### ISSUE TITLE
Feature Request: Log requests

### ISSUE THREAD

**Issue by sdrissen** [Eun/http-server-action#25]
Hi,
you maybe know me better as @tts-sdrissen, but I am now from my private account.

Would you approve a change for logging the requests?
Like to create a log file containing the data send to the server for validation:
POST /endpoint?userId=1 postdata: {"something": "true"}

So I can verify, my project still sends the same requests to the server. I want to redesign my request logic and I want to make sure, everything work the same.

As usual, I would volunteer to implement this, but I would like to have it in your repo, so if you make any changes, I can make use of it. I would make it optional, so that everything work the same with default parameters.

If this is out-of-scope, I can understand it. 

Viele Grüße, Simon

**Comment by tts-sdrissen** [comment]
Thats me

**Comment by Eun** [comment]
Hey, yes that sounds reasonable.
I would love to see this format:
{TIME} {METHOD} {ENDPOINT} {BODY}

If you intent on testing against the logs, I suggest you add two log formats, a console variant that I described above and an json variant that writes to a file.
I think it would be easier for tests to read the json log file (jq could help with that)

**Comment by sdrissen** [comment]
My colleague @tts-jwiebe will do this task. 

Are you confident that there is a console output on a github action? Is the output of the start Eun/http-server-action really outputed and saved after the next step in the workfile has started? I never tested this, but I would assume that console variant you mentioned will be in the void instead of readable in the Action Log.

But yes. We intend to use your action as a offline variant and debug output in this case would be useful. 
Still not sure, if the console output can be monitored in github action.

**Comment by Eun** [comment]
Good catch. I think a log file for both scenarios is best, since the action also keeps running a process after it is marked as done.
