### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by evaristocuesta** [Eun/http-server-action#40]
Hi, 

Would it be interesting to add a path to a custom 404 page?

Thank you. 

Regards, 
Evaristo Cuesta.

**Comment by Eun** [comment]
Hey, at the moment this is not planned, however feel free to open a Pull Request and add this functionality :)

**Comment by evaristocuesta** [comment]
Thank you. I haven't developed a github action before, but I'll give it a try.

**Comment by evaristocuesta** [comment]
Hi, 
I just created the PR
https://github.com/Eun/http-server-action/pull/41

**Comment by Eun** [comment]
Released in [v1.0.12](https://github.com/Eun/http-server-action/releases/tag/v1.0.12)
